### PR TITLE
Solution added for Problem 2 in Python Language

### PR DESCRIPTION
**Pull request by mortalglitch**
This was a fun one. I love the Fibonacci sequence hadn't thought about just summing the evens before. Enjoy! If you need any modifications or clean up let me know. Tried to write it as understandable as possible and include some explanations.

### CODE REVIEW

**Comment by mortalglitch** [comment]
Updated the solution to clarify the results as the sum of evens vs. the total of evens.

**Comment by mortalglitch** [comment]
Trying to follow here to see if I can clean it up a bit.
What would trigger the break down? Like if it was near the max number and happened to consecutively sum up to even it would add one value of C past the correct sum?

**Comment by justkng** [comment]
If there were two consecutive Fibonacci numbers that were even, one less than and the other greater than max number, your solution would include the term that is greater than max number.  However, consecutive Fibonacci numbers are never even, so your solution technically works in all cases.

**Comment by justkng** [comment]
I'd move your c = a+b below your if statement

**Comment by mortalglitch** [comment]
Updated as discussed with justkng.
Moved summation of result to prevent potential logic flaw.

**Pull request merged**
